site_name: Cyber Metric Library
site_description: Cyber Metric Library
site_url: https://www.metricslibrary.net
copyright: Copyright &copy; 2025 Phil Massyn - <a rel="me" href="https://aus.social/@massyn">Mastodon</a>

nav:
  - Home: index.md
  - Library: library.md
  - About: about.md
theme:
  icon:
    logo: fontawesome/solid/book
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.footer
    - navigation.indexes
  name: material
plugins:
  - search
  - mermaid2
  - mkdocs-video
markdown_extensions:
  - toc:
      title: On this page
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.caret
extra:
  analytics:
    provider: google
    property: G-86GYW9MWMM